<?php
    use Src\Core\Functions;
?>

<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= URL ?>/assets/css/style.css">
    <script src="https://kit.fontawesome.com/e6cd06e1cc.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e6cd06e1cc.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <title><?= $data['title'] ?></title>
</head>
<body>
    <nav class="sidebar" data-menu>
        <div class="sidebar_logo-content">
            <div class="logo">
                <span class="logo_logo-name">Menu</span>
            </div>

            <i class='bx bx-menu sidebar_btn' data-menubtn></i>
        </div>

        <ul class="siderbar_nav-list">
            <li class="button-action">
                <a href="/tarefa">
                    <i class='bx bxs-home'></i>
                    <span class="nav-list_link-name">Inicio</span>
                </a>

                <span class="nav-list_tooltip">Inicio</span>
            </li>
            <li>
                <a href="/tarefa">
                    <i class='bx bxs-notepad'></i>
                    <span class="nav-list_link-name">Tarefas</span>
                </a>

                <span class="nav-list_tooltip">Tarefas</span>
            </li>
            <li>
                <a href="/usuario/logout">
                    <i class='bx bx-log-in'></i>
                    <span class="nav-list_link-name">Logout</span>
                </a>

                <span class="nav-list_tooltip">Logout</span>
            </li>
        </ul>
    </nav>

    <div class="content">
        <?php Functions::_loadView($data['view'], $data['params']) ?>
    </div>

    <script src="<?= URL ?>/assets/js/navbar.js"></script>
    <script src="<?= URL ?>/assets/js/mensagem.js"></script>
</body>
</html>